name: MSBuild

on:
  push:
    branches: [ "SteamBranch" ]
  workflow_dispatch:
    branches: [ "SteamBranch" ]

env:
  SOLUTION_FILE_PATH: .  # Chemin vers le fichier de solution (répertoire racine du projet)
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v4
      with:
        name: release
        path: bin/NetCrack-PalWorld.dll
